services:
  lab-runner:
    image: jupyter/base-notebook:latest
    volumes:
      - ../..:/workspaces:cached
    # Removed "depends_on" and "network_mode"
    user: "1000:100"

    # Keeps the container running
    command: sleep infinity